name: Auto Generate Contracts

on:
  schedule:
    # Запускаем каждые 4 часа в рабочие дни (пн-пт)
    - cron: '0 */4 * * 1-5'
  
  # Можно запустить вручную
  workflow_dispatch:

jobs:
  generate-code:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    # Скачиваем код репозитория
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    # Устанавливаем Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    # Запускаем наш скрипт
    - name: Generate contract
      run: |
        python scripts/code_generator.py
    
    # Коммитим изменения
    - name: Commit changes
      run: |
        git config --local user.email "bot@github.com"
        git config --local user.name "Contract Generator Bot"
        
        # Добавляем все изменения
        git add .
        
        # Проверяем есть ли изменения
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "🤖 Auto-generated contract $(date '+%Y-%m-%d %H:%M')"
          git push
        else
          echo "No changes to commit"
        fi
